[app_fri_params.fri_params]
log_blowup = 1
log_final_poly_len = 0
num_queries = 100
proof_of_work_bits = 16

[app_vm_config.system.config]
max_constraint_degree = 3
continuation_enabled = true
num_public_values = 32
profiling = false

[app_vm_config.system.config.memory_config]
addr_space_height = 3
pointer_max_bits = 29
timestamp_max_bits = 29
decomp = 17
max_access_adapter_n = 32

[[app_vm_config.system.config.memory_config.addr_spaces]]
num_cells = 0
min_block_size = 1
layout = "Null"

[[app_vm_config.system.config.memory_config.addr_spaces]]
num_cells = 128
min_block_size = 4
layout = "U8"

[[app_vm_config.system.config.memory_config.addr_spaces]]
num_cells = 536870912
min_block_size = 4
layout = "U8"

[[app_vm_config.system.config.memory_config.addr_spaces]]
num_cells = 32
min_block_size = 4
layout = "U8"

[[app_vm_config.system.config.memory_config.addr_spaces]]
num_cells = 536870912
min_block_size = 1

[app_vm_config.system.config.memory_config.addr_spaces.layout.Native]
size = 4

[[app_vm_config.system.config.memory_config.addr_spaces]]
num_cells = 0
min_block_size = 1

[app_vm_config.system.config.memory_config.addr_spaces.layout.Native]
size = 4

[[app_vm_config.system.config.memory_config.addr_spaces]]
num_cells = 0
min_block_size = 1

[app_vm_config.system.config.memory_config.addr_spaces.layout.Native]
size = 4

[[app_vm_config.system.config.memory_config.addr_spaces]]
num_cells = 0
min_block_size = 1

[app_vm_config.system.config.memory_config.addr_spaces.layout.Native]
size = 4

[[app_vm_config.system.config.memory_config.addr_spaces]]
num_cells = 0
min_block_size = 1

[app_vm_config.system.config.memory_config.addr_spaces.layout.Native]
size = 4

[app_vm_config.rv32i]

[app_vm_config.io]

[app_vm_config.keccak]

[app_vm_config.sha256]

[app_vm_config.native]

[app_vm_config.castf]

[app_vm_config.rv32m]
range_tuple_checker_sizes = [256, 2048]

[app_vm_config.modular]
supported_moduli = ["4002409555221667393417789825735904156556882819939007885332058136124031650490837864442687629129015664037894272559787", "52435875175126190479447740508185965837690552500527637822603658699938581184513"]

[app_vm_config.fp2]
supported_moduli = [["Bls12_381Fp2", "4002409555221667393417789825735904156556882819939007885332058136124031650490837864442687629129015664037894272559787"]]

[app_vm_config.pairing]
supported_curves = ["Bls12_381"]

[[app_vm_config.ecc.supported_curves]]
struct_name = "Bls12_381G1Affine"
modulus = "4002409555221667393417789825735904156556882819939007885332058136124031650490837864442687629129015664037894272559787"
scalar = "52435875175126190479447740508185965837690552500527637822603658699938581184513"
a = "0"
b = "4"

[leaf_fri_params.fri_params]
log_blowup = 1
log_final_poly_len = 0
num_queries = 100
proof_of_work_bits = 16

[compiler_options]
word_size = 8
enable_cycle_tracker = false

[agg_config]
max_num_user_public_values = 32
profiling = false
root_max_constraint_degree = 9

[agg_config.leaf_fri_params]
log_blowup = 1
log_final_poly_len = 0
num_queries = 100
proof_of_work_bits = 16

[agg_config.internal_fri_params]
log_blowup = 2
log_final_poly_len = 0
num_queries = 44
proof_of_work_bits = 16

[agg_config.root_fri_params]
log_blowup = 3
log_final_poly_len = 0
num_queries = 30
proof_of_work_bits = 16

[agg_config.compiler_options]
word_size = 8
enable_cycle_tracker = false
